### ISSUE TITLE
model pruning

### ISSUE THREAD

**Issue by loganwu0526** [JiayuanWang-JW/YOLOv8-multi-task#35]
I try to apply the torch-pruning (code from https://github.com/VainF/Torch-Pruning/tree/master/examples/yolov8) to your model, but the following error message appear.

WARNING ⚠️ /home/lewin/YOLOv8-multi-task/ultralytics/runs/detect/yolov8s_trn007/weights/[best.pt](http://best.pt/) appears to require 'ultralytics.utils', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.utils' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=[yolov8n.pt](http://yolov8n.pt/)'
requirements: Ultralytics requirement "ultralytics.utils" not found, attempting AutoUpdate...
requirements: ❌ AutoUpdate skipped (offline)

Do you have any idea how to solve this issue

thanks

**Comment by JiayuanWang-JW** [comment]
We strongly recommend you create a pure environment and follow our instructions to build yours. Otherwise, you may encounter some issues because the YOLOv8 has many mechanisms to detect your environment package automatically. Then it will change some variable values to further affect the code running.

Please use the below command instead of the YOLOv8 official other install command. 

cd YOLOv8-multi-task
pip install -e .

**Comment by loganwu0526** [comment]
> We strongly recommend you create a pure environment and follow our instructions to build yours. Otherwise, you may encounter some issues because the YOLOv8 has many mechanisms to detect your environment package automatically. Then it will change some variable values to further affect the code running.
> 
> Please use the below command instead of the YOLOv8 official other install command.
> 
> cd YOLOv8-multi-task pip install -e .
I actually follow your instruction and build a clear environment and got this error message
